const fs = require('fs');
const path = require('path');

const ERA_NAMES = {
  primitive: 'Primitive',
  agriculture: 'Agriculture',
  bronze: 'Bronze Age',
  iron: 'Iron Age',
  steam: 'Steam Age',
  electric: 'Electric Age',
  info: 'Information Age'
};

function readWorldData(worldsDir, dir) {
  try {
    const configPath = path.join(worldsDir, dir, 'config.json');
    const statePath = path.join(worldsDir, dir, 'state.json');
    if (!fs.existsSync(configPath) || !fs.existsSync(statePath)) return null;
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const state = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    return { id: dir, config, state };
  } catch (e) {
    return null;
  }
}

function generateReadme(worlds) {
  const total = worlds.length;
  const totalPop = worlds.reduce((s, w) => s + (w.state.stats.total_population || 0), 0);
  const totalSettlements = worlds.reduce((s, w) => s + (w.state.stats.total_settlements || 0), 0);
  const totalYears = worlds.reduce((s, w) => s + (w.state.year || 0), 0);
  const totalLikes = worlds.reduce((s, w) => s + ((w.state.stats && w.state.stats.likes) || 0), 0);
  const topWorld = worlds.sort((a, b) => (b.state.stats.total_population || 0) - (a.state.stats.total_population || 0))[0];

  const lines = [];

  lines.push('# Dust World: Multiverse');
  lines.push('');
  lines.push('A self-evolving virtual world cluster platform powered by GitHub Actions.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Universe Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Active Worlds | ${total} |`);
  lines.push(`| Total Population | ${totalPop.toLocaleString()} |`);
  lines.push(`| Total Settlements | ${totalSettlements.toLocaleString()} |`);
  lines.push(`| Cumulative Years | ${totalYears.toLocaleString()} |`);
  lines.push(`| Total Likes | ${totalLikes} |`);
  if (topWorld) {
    lines.push(`| Most Populous | ${topWorld.config.name || topWorld.id} (${(topWorld.state.stats.total_population || 0).toLocaleString()}) |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## World Rankings');
  lines.push('');
  lines.push('### By Population');
  lines.push('');
  lines.push('| # | World | Creator | Year | Era | Settlements | Population | Likes | Updated |');
  lines.push('|---|-------|---------|------|-----|-------------|------------|-------|---------|');

  const sorted = worlds.sort((a, b) => (b.state.stats.total_population || 0) - (a.state.stats.total_population || 0));
  sorted.forEach((w, i) => {
    const name = w.config.name || w.id;
    const creator = w.config.creator || 'anonymous';
    const year = w.state.year || 0;
    const era = ERA_NAMES[w.state.era] || w.state.era || 'unknown';
    const settlements = w.state.stats.total_settlements || 0;
    const pop = w.state.stats.total_population || 0;
    const likes = (w.state.stats && w.state.stats.likes) || 0;
    const updated = w.state.last_updated ? new Date(w.state.last_updated).toISOString().split('T')[0] : '-';
    lines.push(`| ${i + 1} | ${name} | ${creator} | ${year} | ${era} | ${settlements} | ${pop.toLocaleString()} | ${likes} | ${updated} |`);
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## All Worlds');
  lines.push('');

  worlds.forEach(w => {
    const name = w.config.name || w.id;
    const creator = w.config.creator || 'anonymous';
    const year = w.state.year || 0;
    const era = ERA_NAMES[w.state.era] || w.state.era || 'unknown';
    const pop = w.state.stats.total_population || 0;
    const settlements = w.state.stats.total_settlements || 0;
    const desc = w.config.description || '';
    lines.push(`### ${name}`);
    lines.push(`- **ID:** \`${w.id}\``);
    lines.push(`- **Creator:** ${creator}`);
    lines.push(`- **Year:** ${year} | **Era:** ${era}`);
    lines.push(`- **Population:** ${pop.toLocaleString()} | **Settlements:** ${settlements}`);
    if (desc) lines.push(`- **Description:** ${desc}`);
    lines.push('');
  });

  lines.push('---');
  lines.push('');
  lines.push('*Auto-generated by World Evolution Bot. Updated every 30 minutes.*');

  return lines.join('\n');
}

async function main() {
  const worldsDir = path.join(__dirname, '..', 'data', 'worlds');
  const readmePath = path.join(__dirname, '..', 'README.md');

  if (!fs.existsSync(worldsDir)) {
    console.log('No worlds directory, writing empty README');
    const empty = '# Dust World: Multiverse\n\nNo worlds created yet. Create the first world to begin the simulation.\n';
    fs.writeFileSync(readmePath, empty);
    return;
  }

  const dirs = fs.readdirSync(worldsDir).filter(d => {
    const p = path.join(worldsDir, d);
    return fs.statSync(p).isDirectory();
  });

  const worlds = dirs.map(d => readWorldData(worldsDir, d)).filter(w => w !== null);

  if (worlds.length === 0) {
    const empty = '# Dust World: Multiverse\n\nNo active worlds found. Check data/worlds/ for world data.\n';
    fs.writeFileSync(readmePath, empty);
    console.log('No valid worlds found, wrote empty README');
    return;
  }

  const readme = generateReadme(worlds);
  fs.writeFileSync(readmePath, readme);
  console.log(`README updated with ${worlds.length} worlds`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
